db-config {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    url = "jdbc:postgresql://localhost:5432/postgres"
    user = "postgres"
    password = "password123"
    driver = "org.postgresql.Driver"
    connectionPool = HikariCP
    keepAliveConnection = true
  }
}

jwt {
  issuer = "stream-api"
  audience = "stream-clients"
  secret = "sachinsharma7677159926@scala"
  access-token-ttl-minutes = 15
  refresh-token-ttl-days = 7
}
